spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: name
    url: jdbc:h2:file:./data/testdb
    password: password
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
